### ISSUE TITLE
Support standalone mode

### ISSUE THREAD

**Issue by ngiger** [saltstack-formulas/letsencrypt-formula#14]
I am working on a patch to support the standalone mode. It should allow
- stop service (e.g. apache or nginx)
- call letsencrypt-auto  standalone 
- restart service (e.g. apache or nginx)

This is needed in my setup, as the roots for my virtual hosts don't follow (for historical reason) a very clear pattern, and I can assume a small downtime during the night easily.

**Comment by thomasrossetto** [comment]
+1

edit: @ngiger you can put 'standalone' value in authenticator key on pillar file
