### ISSUE TITLE
Cron job doesn't handle service reloads.

### ISSUE THREAD

**Issue by gravyboat** [saltstack-formulas/letsencrypt-formula#15]
I noticed my certs were renewing but the nginx service wasn't getting the new certs, This is an issue with the cron job here: https://github.com/saltstack-formulas/letsencrypt-formula/blob/0a8279321906fbc1391fc196667d422da78d9d2a/letsencrypt/domains.sls#L42. I'm not sure exactly how I want to handle reloading the service, but we should probably consider it in some form.

**Comment by lgunsch** [comment]
This happens with many other services too, for example dovecot, postfix, and pound.

One solution, I suppose, could be to have a configurable list of services written to a sourced file, which would then be restarted after the certificates are renewed.

**Comment by iggy** [comment]
Or maybe something in the README that says something like "You can add an additional cron job after this to restart your services with the following line:...."
