### ISSUE TITLE
Error with multiple domains

### ISSUE THREAD

**Issue by HerHde** [saltstack-formulas/letsencrypt-formula#16]
Hey @lgunsch, hey guys,
6cad4d7959e7797e666d03a4baad31cca21cc46c adds a loop `{% for domain in domainlist %}`, which throws errors in case of multiple domains per set. Something like `{{ setname }}-{{ domainlist[0] }}` should do the thing.

Greetings
~HerHde

**Comment by lgunsch** [comment]
I can check it out and open a fixing pull request.

**Comment by HerHde** [comment]
BTW: Why do you cat the privatekey and the fullchain-certs together?

**Comment by lgunsch** [comment]
Some reverse proxies or SSL terminators like Pound require this format, and don't work with the fullchain and private key separated.

**Comment by iggy** [comment]
So can we get a fix for this or someone send a PR to revert the change until it can be fixed? I'll gladly merge either one, but I don't like leaving the formulas sitting around broken.

**Comment by lgunsch** [comment]
I'll open a pull request to fix the issue today.

**Comment by lgunsch** [comment]
@HerHde Can you post a log of the error, and perhaps an example pillar file? I am having trouble replicating the issue here. The `domain.sls` states file seems to be rendered as expected with the example in `pillar.example` 

Also note that using `domainlist[0]` will not work in this case, because there must be a `create-fullchain-privkey-pem-for-` state for each domain in every domain set.

**Comment by HerHde** [comment]
Okay, here we go:
Excerpt from the pillar:

```
  domainsets:
    www:
      - domain.com
      - www.domain.com
      - git.domain.com
      - mumble.domain.com
      - owncloud.domain.com
```

Now the weird thing: The tests succeed. One day after I used this to create **one** cert (domain.com) with the other domains as SANs, there were created singe certs for every domain by the crontab at 7:12 am.
I hate it when it comes to such a string of failures.
This will make up another Issue, but to answer your question, the tests _create-fullchain-privkey-pem-for-domain.com_ failed but for the first one, reporting that the directory or file (e.g. _/live/git.domain.com/_) does not exist.
As I understand the structure of the domain sets, the first domain of every set (_domain.com_) is the CommonName, the following ones are SubjectAlternativeNames (_www.domain.com_), so there should be one cert for every set of domains (_www_).

**Comment by lgunsch** [comment]
On your server, does there exist an `/etc/letsencrypt/live/{domain}/` directory for each of the domains in each domain set?

**Comment by lgunsch** [comment]
Okay, I think I understand now. I switched the single call with a looped call because I didn't realize the domain-sets were for a CommonName and SubjectAlternativeNames, and I thought it would create a new cert for each domain (which would then need a `cat` for each domain).

**Comment by lgunsch** [comment]
@HerHde  I have what I believe is a fix, and I have tested it out with my own domain and multiple fake domains. However, it would be great if you could give https://github.com/lgunsch/letsencrypt-formula/tree/issue-16 a run to make sure it works in your case.

**Comment by HerHde** [comment]
> On your server, does there exist an /etc/letsencrypt/live/{domain}/ directory for each of the domains in each domain set?

Yes, the cronjob created them. For the further testing, I deleted them.

Your fix succeds in my environment, including the cronjob. No errors from salt, no other directories than the CN one, everything seems fine, even with a second set of domains.
Good work, thank you ;-)
