### ISSUE TITLE
Support certbot distribution package 

### ISSUE THREAD

**Issue by Talkless** [saltstack-formulas/letsencrypt-formula#38]
Hi,

I would like to suggest to add support for `certbot` installed from distribution packages:
[Debian](https://packages.debian.org/search?keywords=certbot)
[Ubuntu](http://packages.ubuntu.com/search?keywords=certbot&searchon=names&suite=all&section=all)

`letsencrypt-client-git` state could be renamed to generic `letsencrypt-client` and it would use `package.installed` or `git.latest` depending on pillar `letsencrypt:use_distribution_client` value, for example.

There is a little problem with Debian Jessie, as `jessie-backports` repository has to be configured additionally. In my setup, I have my own `repository.backports` state that I include where it's needed for some packages, and I wouldn't like that some salt formula would add yet another `sources.list.d/backports.list` file, so I guess repository requirement exercise could be left for the user.

Using packaged `certbot`, paths like `/etc/letsencrypt/live/` should be changed accordingly.

I guess I could prepare PR if agreement is arrived at.

**Comment by Talkless** [comment]
I've found [alternative letsencrypt formula](https://github.com/salt-formulas/salt-formula-letsencrypt) that supports "source: pkg" and other sources. It would be nice to have single formula with all the best...

**Comment by javierbertoli** [comment]
Fixed on #43.
