### ISSUE TITLE
Why renewing manually instead of using certbot?

### ISSUE THREAD

**Issue by syphernl** [saltstack-formulas/letsencrypt-formula#39]
Certbot has a `renew` option which will renew all certificates that are close to renewal date. ISTM that this would be a better approach than using `renew_letsencrypt_cert.sh` and `check_letsencrypt_cert.sh` ot is there a specific reason why `certbot renew` cannot be used?

**Comment by Talkless** [comment]
Yeah, looks like alternative [salt-formula-letsencrypt](https://github.com/salt-formulas/salt-formula-letsencrypt/blob/master/letsencrypt/files/certbot.service#L14) has done it right.

**Comment by pankajghadge** [comment]
Will it be possible to add --renew-hook "/usr/local/bin/renew.sh" something like that to restart the services like haproxy or nginx or apache

**Comment by javierbertoli** [comment]
Fixed on #43.
