### ISSUE TITLE
Faulty renew check

### ISSUE THREAD

**Issue by kossmac** [saltstack-formulas/letsencrypt-formula#50]
PR #42 broke the renew check. Line 11 in [https://github.com/saltstack-formulas/letsencrypt-formula/blob/master/letsencrypt/files/renew_letsencrypt_cert.sh.jinja](https://github.com/saltstack-formulas/letsencrypt-formula/blob/master/letsencrypt/files/renew_letsencrypt_cert.sh.jinja#L11) must read as follows:
`if ! /usr/local/bin/check_letsencrypt_cert.sh "$@" > /dev/null`

Or am I missing something?

**Comment by javierbertoli** [comment]
You're right. My bad, submitted #51 to address this.
