### ISSUE TITLE
Dangerous force-renew in example pillar

### ISSUE THREAD

**Issue by jinnatar** [saltstack-formulas/letsencrypt-formula#58]
https://github.com/saltstack-formulas/letsencrypt-formula/blob/96101bcb676348265871683395e2f0523dccf8b0/pillar.example#L17

This sets renewing to force mode, which with the timers means the certs get force renewed twice a day. This means you'll be rate-limited in no time. I recommend switching it to False in the example.

**Comment by mrichar1** [comment]
I've just discovered that setting `renew-by-default: False` doesn't work - I think that this is used as a flag, not a boolean so the value is irrelevant.

Only by completely removing this line do things work properly.

**Comment by javierbertoli** [comment]
This was fixed, following @Artanicus suggestions, in #73
